import { Inter } from "next/font/google";
import "./globals.css";
// _app.js or _app.tsx
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import NavBar from "./components/navBar/NavBar";
import NewNavBar from "./components/NewNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nimbus Nex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NewNavBar />
        <div className="min-h-[100vh] relative bg-[#fffbe3] text-black mt-36 md:mt-56 ">
          {" "}
          {children}
        </div>
      </body>
    </html>
  );
}
