import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar/NavBar";
import NewNavBar from "./components/NewNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nimbus Nex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NewNavBar />
        {children}
      </body>
    </html>
  );
}
